# -*- coding: utf-8 -*-
"""student_year.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8bP9ftd94_ROaAM4fu-A8Z85tyA7VEE
"""

#upload the file from local computer to the google server
from google.colab import files
uploaded = files.upload()

# upload the data in dataframe
import pandas as pd
df = pd.read_csv('student_year.csv')
df.head()

#plotting the bar diagram x axis=year and y-axis=passed
import matplotlib.pyplot as plt
plt.bar(df['Year'],df['Passed'])
plt.show()

# spliting the training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df[['Year']],df['Passed'],test_size=0.2)

x_train

x_test

#import linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

#predict the y_predict and convert the flot no in integer
y_predict = model.predict(x_test)
y_predict = y_predict.astype(int)
y_predict

#mean absolute error
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
mae = mean_absolute_error(y_test,y_predict)
mse=mean_squared_error(y_test,y_predict)
rse=root_mean_squared_error(y_test,y_predict)
print(mae)
print(mse)
rse

int(model.predict([[2026]]))